# Generated by Django 5.0.6 on 2024-06-12 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('endDate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('effort', models.FloatField(blank=True, null=True)),
                ('effortUnit', models.CharField(blank=True, db_column='effortUnit', default='hour', max_length=255, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('durationUnit', models.CharField(blank=True, db_column='durationUnit', default='day', max_length=255, null=True)),
                ('percentDone', models.FloatField(blank=True, db_column='percentDone', default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('schedulingMode', models.CharField(blank=True, db_column='schedulingMode', max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('constraintType', models.CharField(blank=True, db_column='constraintType', max_length=255, null=True)),
                ('constraintDate', models.DateTimeField(blank=True, db_column='constraintDate', null=True)),
                ('manuallyScheduled', models.BooleanField(blank=True, db_column='manuallyScheduled', default=False, null=True)),
                ('effortDriven', models.BooleanField(blank=True, db_column='effortDriven', default=False, null=True)),
                ('inactive', models.BooleanField(blank=True, default=False, null=True)),
                ('cls', models.CharField(blank=True, max_length=255, null=True)),
                ('iconCls', models.CharField(blank=True, db_column='iconCls', max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('parentIndex', models.IntegerField(blank=True, db_column='parentIndex', default=0, null=True)),
                ('expanded', models.BooleanField(blank=True, default=False, null=True)),
                ('calendar', models.IntegerField(blank=True, default=0, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('unscheduled', models.BooleanField(blank=True, default=False, null=True)),
                ('ignoreResourceCalendar', models.BooleanField(blank=True, default=False, null=True)),
                ('delayFromParent', models.IntegerField(blank=True, db_column='delayFromParent', default=0, null=True)),
                ('projectConstraintResolution', models.CharField(blank=True, db_column='projectConstraintResolution', default='', max_length=255, null=True)),
                ('baselines', models.JSONField(blank=True, null=True)),
                ('parentId', models.ForeignKey(blank=True, db_column='parentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='gantt.task')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, default=2, null=True)),
                ('cls', models.CharField(blank=True, max_length=255, null=True)),
                ('lag', models.FloatField(blank=True, default=0, null=True)),
                ('lagUnit', models.CharField(blank=True, db_column='lagUnit', default='day', max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('fromSide', models.CharField(blank=True, db_column='fromSide', max_length=255, null=True)),
                ('toSide', models.CharField(blank=True, db_column='toSide', max_length=255, null=True)),
                ('fromEvent', models.ForeignKey(blank=True, db_column='fromEvent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencies_from', to='gantt.task')),
                ('toEvent', models.ForeignKey(blank=True, db_column='toEvent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencies_to', to='gantt.task')),
            ],
            options={
                'db_table': 'dependencies',
            },
        ),
    ]
